// Copyright 2025 Google LLC
// SPDX-License-Identifier: Apache-2.0

using System.CommandLine;

namespace GoogleAdk.Dev.Cli;

/// <summary>
/// The "create" command — scaffolds a new agent project.
/// Usage: adk create [agent_name] [--model MODEL] [--project PROJECT] [--region REGION]
/// </summary>
public static class CreateCommand
{
    private const string DefaultModel = "gemini-2.5-flash";

    public static Command Create()
    {
        var agentNameArg = new Argument<string>("agent_name")
        {
            Description = "Name of the agent to create.",
        };

        var modelOption = new Option<string>("--model")
        {
            Description = "The model to use.",
            DefaultValueFactory = _ => DefaultModel,
        };

        var projectOption = new Option<string?>("--project")
        {
            Description = "Google Cloud project ID.",
        };

        var regionOption = new Option<string?>("--region")
        {
            Description = "Google Cloud region.",
        };

        var apiKeyOption = new Option<string?>("--api-key")
        {
            Description = "Google API key (for non-Vertex AI usage).",
        };

        var forceOption = new Option<bool>("--yes", "-y")
        {
            Description = "Overwrite existing directory without prompting.",
            DefaultValueFactory = _ => false,
        };

        var command = new Command("create", "Create a new agent project.");
        command.Arguments.Add(agentNameArg);
        command.Options.Add(modelOption);
        command.Options.Add(projectOption);
        command.Options.Add(regionOption);
        command.Options.Add(apiKeyOption);
        command.Options.Add(forceOption);

        command.SetAction(async parseResult =>
        {
            var agentName = parseResult.GetValue(agentNameArg);
            var model = parseResult.GetValue(modelOption);
            var project = parseResult.GetValue(projectOption);
            var region = parseResult.GetValue(regionOption);
            var apiKey = parseResult.GetValue(apiKeyOption);
            var force = parseResult.GetValue(forceOption);

            await CreateAgentAsync(agentName!, model!, project, region, apiKey, force);
        });

        return command;
    }

    private static async Task CreateAgentAsync(
        string agentName, string model, string? project, string? region, string? apiKey, bool force)
    {
        var agentDir = Path.Combine(Directory.GetCurrentDirectory(), agentName);

        if (Directory.Exists(agentDir))
        {
            if (!force)
            {
                Console.Write($"Directory '{agentName}' already exists. Overwrite? (y/N) ");
                var response = Console.ReadLine();
                if (!string.Equals(response, "y", StringComparison.OrdinalIgnoreCase))
                {
                    Console.WriteLine("Cancelled.");
                    return;
                }
            }
            Directory.Delete(agentDir, recursive: true);
        }

        Directory.CreateDirectory(agentDir);

        // Generate .csproj
        var csprojContent = GenerateCsproj(agentName);
        await File.WriteAllTextAsync(Path.Combine(agentDir, $"{agentName}.csproj"), csprojContent);

        // Generate Program.cs
        var programContent = GenerateProgram(agentName, model);
        await File.WriteAllTextAsync(Path.Combine(agentDir, "Program.cs"), programContent);

        // Generate .env file
        var envContent = GenerateEnvFile(project, region, apiKey);
        if (!string.IsNullOrWhiteSpace(envContent))
            await File.WriteAllTextAsync(Path.Combine(agentDir, ".env"), envContent);

        Console.WriteLine($"Agent project '{agentName}' created at: {agentDir}");
        Console.WriteLine();
        Console.WriteLine("To get started:");
        Console.WriteLine($"  cd {agentName}");
        Console.WriteLine($"  dotnet run");
    }

    private static string GenerateCsproj(string agentName)
    {
        return $"""
            <Project Sdk="Microsoft.NET.Sdk">
            
              <PropertyGroup>
                <OutputType>Exe</OutputType>
                <TargetFramework>net10.0</TargetFramework>
                <ImplicitUsings>enable</ImplicitUsings>
                <Nullable>enable</Nullable>
                <RootNamespace>{agentName}</RootNamespace>
              </PropertyGroup>
            
              <ItemGroup>
                <PackageReference Include="GoogleAdk.Core" Version="*" />
                <PackageReference Include="GoogleAdk.Models.Gemini" Version="*" />
              </ItemGroup>
            
            </Project>
            """;
    }

    private static string GenerateProgram(string agentName, string model)
    {
        return $$"""
            // Auto-generated by ADK CLI
            using GoogleAdk.Core;
            using GoogleAdk.Core.Agents;
            using GoogleAdk.Core.Abstractions.Models;
            
            // Define a simple tool
            var getCurrentTime = new FunctionTool(
                name: "get_current_time",
                description: "Returns the current time in a specified city.",
                handler: (args, context) =>
                {
                    var city = args.TryGetValue("city", out var c) ? c?.ToString() : "unknown";
                    return Task.FromResult<object?>(new { status = "success", report = $"The current time in {city} is {DateTime.UtcNow:HH:mm} UTC" });
                },
                parameters: new Dictionary<string, object?>
                {
                    ["type"] = "object",
                    ["properties"] = new Dictionary<string, object?>
                    {
                        ["city"] = new Dictionary<string, object?> { ["type"] = "string", ["description"] = "The city name" }
                    },
                    ["required"] = new[] { "city" }
                });
            
            // Create the agent
            var agent = new LlmAgent(new LlmAgentConfig
            {
                Name = "{{agentName}}",
                ModelName = "{{model}}",
                Description = "A helpful assistant that tells the current time.",
                Instruction = "You are a helpful assistant. Use the get_current_time tool when asked about time.",
                Tools = new List<IBaseTool> { getCurrentTime },
            });
            
            Console.WriteLine($"Agent '{{agentName}}' is ready!");
            """;
    }

    private static string GenerateEnvFile(string? project, string? region, string? apiKey)
    {
        var lines = new List<string>();
        if (!string.IsNullOrEmpty(apiKey))
        {
            lines.Add($"GOOGLE_API_KEY={apiKey}");
            lines.Add("GOOGLE_GENAI_USE_VERTEXAI=0");
        }
        if (!string.IsNullOrEmpty(project))
            lines.Add($"GOOGLE_CLOUD_PROJECT={project}");
        if (!string.IsNullOrEmpty(region))
            lines.Add($"GOOGLE_CLOUD_LOCATION={region}");
        if (!string.IsNullOrEmpty(project) && !string.IsNullOrEmpty(region))
            lines.Add("GOOGLE_GENAI_USE_VERTEXAI=1");
        return string.Join(Environment.NewLine, lines);
    }
}
