using GoogleAdk.Core.Abstractions.Tools;

namespace GoogleAdk.E2e.Tests;

/// <summary>
/// Tools generated by the ADK source generator for streaming E2E tests.
/// </summary>
public static partial class StreamingTestTools
{
    /// <summary>Returns the current weather for a city.</summary>
    /// <param name="city">The city name to get weather for.</param>
    [FunctionTool]
    public static string GetWeather(string city)
    {
        return city.ToLowerInvariant() switch
        {
            "london" => "Cloudy, 14°C",
            "tokyo" => "Sunny, 22°C",
            "sydney" => "Rainy, 18°C",
            _ => $"Partly cloudy, 20°C in {city}"
        };
    }

    /// <summary>Returns the current time in a timezone.</summary>
    /// <param name="timezone">IANA timezone name, e.g. Europe/London.</param>
    [FunctionTool]
    public static string GetCurrentTime(string timezone)
    {
        try
        {
            var tz = TimeZoneInfo.FindSystemTimeZoneById(timezone);
            var now = TimeZoneInfo.ConvertTimeFromUtc(DateTime.UtcNow, tz);
            return $"{now:HH:mm} in {timezone}";
        }
        catch
        {
            return $"12:00 in {timezone}";
        }
    }

    /// <summary>Adds two numbers together.</summary>
    /// <param name="a">First number.</param>
    /// <param name="b">Second number.</param>
    [FunctionTool]
    public static double Add(double a, double b) => a + b;
}
